# Note that mongo container is started before Orion, as Orion needs it
# as dependency and reserve the order has been found problematic in some
# low resource hosts
version: "3"
services:
  mongo:
    image: mongo:4.4
    command: --nojournal
  orion:
    image: fiware/orion-ld:latest
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
